fixes:
    - "ballerina/graphql/**/::../ballerina/"

ignore:
    - "ballerina-tests"

coverage:
    precision: 2
    round: down
    range: "60...80"
    status:
        project:
            default:
                target: 80
