fixes:
    - "ballerina/graphql/*/::../ballerina/"

ignore:
    - "ballerina-tests"
    - "compiler-plugin-tests"
    - "compiler-plugin"
    - "commons"

coverage:
    precision: 2
    round: down
    range: "60...80"
    status:
        project:
            default:
                target: 80

codecov:
    max_report_age: off
