[[dependency]]
org = "ballerina"
name = "encoding"
version = "1.0.9"

[[dependency]]
org = "ballerina"
name = "file"
version = "0.6.5"

[[dependency]]
org = "ballerina"
name = "http"
version = "1.0.7"

[[dependency]]
org = "ballerina"
name = "io"
version = "0.5.7"
