// Copyright (c) 2021 WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
//
// WSO2 Inc. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

public final readonly & table<LiftRecord> key(id) liftTable = table [
    { id: "astra-express", name: "Astra Express", status: OPEN, capacity: 10, night: false, elevationGain: 20 },
    { id: "jazz-cat", name: "Jazz Cat", status: CLOSED, capacity: 5, night: true, elevationGain: 30 },
    { id: "jolly-roger", name: "Jolly Roger", status: CLOSED, capacity: 8, night: true, elevationGain: 10 },
    { id: "neptune-rope", name: "Neptune Rope", status: "OPEN", capacity: 1, night: false, elevationGain: 50 },
    { id: "panorama", name: "Panorama", status: "OPEN", capacity: 8, night: false, elevationGain: 2800 },
    { id: "prickly-peak", name: "Prickly Peak", status: "OPEN", capacity: 3, night: false, elevationGain: 1700 },
    { id: "snowtooth-express", name: "Snowtooth Express", status: "OPEN", capacity: 6, night: false, elevationGain: 1480 },
    { id: "summit", name: "Summit", status:"CLOSED", capacity:6, night:false, elevationGain:1480 },
    { id: "wallys", name: "Wally's", status:"HOLD", capacity:2, night:false, elevationGain:820 },
    { id: "western-states", name: "Western States", status:"CLOSED", capacity:6, night:false, elevationGain:1330 },
    { id: "whirlybird", name: "Whirlybird", status:"HOLD", capacity:2, night:false, elevationGain:1003 }
];

public final readonly & table<TrailRecord> key(id) trailTable = table [
    { id: "blue-bird", name: "Blue Bird", status: OPEN, difficulty: "intermediate", groomed: true, trees: false, night: false },
    { id: "blackhawk", name: "Blackhawk", status: OPEN, difficulty: "intermediate", groomed: true, trees: false, night: false },
    { id: "ducks-revenge", name: "Duck's Revenge", status: CLOSED, difficulty: "expert", groomed: true, trees: false, night: false },
    { id: "ice-streak", name: "Ice Streak", status: "OPEN", difficulty: "intermediate", groomed: false, trees: false, night: false },
    { id: "parachute", name: "Parachute", status: "OPEN", difficulty: "intermediate", groomed: false, trees: false, night: false },
    { id: "goosebumps", name: "Goosebumps", status: "OPEN", difficulty: "advanced", groomed: false, trees: true, night: false },
    { id: "river-run", name: "River Run", status: "OPEN", difficulty: "intermediate", groomed: false, trees: true, night: false },
    { id: "cape-cod", name: "Cape Cod", status: "CLOSED", difficulty: "intermediate", groomed: false, trees: true, night: false },
    { id: "grandma", name: "Grandma", status: "OPEN", difficulty: "expert", groomed: false, trees: true, night: false },
    { id: "wild-child", name: "Wild Child", status: "CLOSED", difficulty: "advanced", groomed: false, trees: false, night: false },
    { id: "old-witch", name: "Old Witch", status: "OPEN", difficulty: "expert", groomed: false, trees: true, night: false },
    { id: "dance-fight", name: "Dance Fight", status: "OPEN", difficulty: "beginner", groomed: true, trees: false, night: true },
    { id: "sneaky-pete", name: "Sneaky Pete", status: "OPEN", difficulty: "beginner", groomed: true, trees: false, night: true },
    { id: "bear-cave", name: "Bear Cave", status: "OPEN", difficulty: "intermediate", groomed: true, trees: false, night: true },
    { id: "humpty-dumpty", name: "Humpty Dumpty", status: "CLOSED", difficulty: "intermediate", groomed: false, trees: false, night: false },
    { id: "meatball", name: "Meatball", status: "OPEN", difficulty: "beginner", groomed: true, trees: false, night: true },
    { id: "early-riser", name: "Early Riser", status: "OPEN", difficulty: "intermediate", groomed: true, trees: false, night: true },
    { id: "sunset", name: "Sunset", status: "OPEN", difficulty: "intermediate", groomed: true, trees: false, night: true },
    { id: "home-run", name: "Home Run", status: "OPEN", difficulty: "beginner", groomed: true, trees: false, night: false },
    { id: "crosscut", name: "Crosscut", status: "OPEN", difficulty: "beginner", groomed: true, trees: false, night: false },
    { id: "ocean-breeze", name: "Ocean Breeze", status: "OPEN", difficulty: "intermediate", groomed: false, trees: true, night: true },
    { id: "songstress", name: "Songstress", status: "CLOSED", difficulty: "expert", groomed: false, trees: true, night: false },
    { id: "mountain-run", name: "Mountain Run", status: "OPEN", difficulty: "intermediate", groomed: true, trees: false, night: true },
    { id: "summit-saunter", name: "Summit Saunter", status: "OPEN", difficulty: "intermediate", groomed: true, trees: false, night: true },
    { id: "hemmed-slacks", name: "Hemmed Slacks", status: "OPEN", difficulty: "intermediate", groomed: false, trees: true, night: false },
    { id: "davids-dive", name: "David's Dive", status: "CLOSED", difficulty: "advanced", groomed: false, trees: true, night: false },
    { id: "quarry-chute", name: "Quarry Chute", status: "CLOSED", difficulty: "expert", groomed: false, trees: true, night: false },
    { id: "crooked-chute", name: "Crooked Chute", status: "OPEN", difficulty: "expert", groomed: false, trees: true, night: false },
    { id: "marks-chute", name: "Mark's Chute", status: "OPEN", difficulty: "expert", groomed: false, trees: true, night: false },
    { id: "the-terrible-chute", name: "The Terrible Chute", status: "OPEN", difficulty: "expert", groomed: false, trees: true, night: false },
    { id: "magma-chute", name: "Magma Chute", status: "OPEN", difficulty: "expert", groomed: false, trees: true, night: false },
    { id: "saddleback-chute", name: "Saddleback Chute", status: "OPEN", difficulty: "expert", groomed: false, trees: true, night: false },
    { id: "omega-chute", name: "Omega Chute", status: "OPEN", difficulty: "intermediate", groomed: false, trees: true, night: false },
    { id: "adirondack-chute", name: "Adirondack Chute", status: "OPEN", difficulty: "expert", groomed: false, trees: true, night: false },
    { id: "chicken-out-traverse", name: "Chicken Out Traverse", status: "OPEN", difficulty: "intermediate", groomed: true, trees: false, night: false },
    { id: "blue-streak", name: "Blue Streak", status: "OPEN", difficulty: "advanced", groomed: false, trees: false, night: false },
    { id: "hoya-saxa", name: "Hoya Saxa", status: "OPEN", difficulty: "advanced", groomed: false, trees: true, night: false },
    { id: "michigan-ave", name: "Michigan Ave", status: "OPEN", difficulty: "intermediate", groomed: true, trees: false, night: false },
    { id: "parker-downhill", name: "Parker Downhill", status: "OPEN", difficulty: "advanced", groomed: true, trees: false, night: false },
    { id: "wiggle-waggle", name: "Wiggle Waggle", status: "OPEN", difficulty: "beginner", groomed: true, trees: false, night: false },
    { id: "meow-face", name: "Meow Face", status: "OPEN", difficulty: "intermediate", groomed: true, trees: false, night: false },
    { id: "golden-ticket", name: "Golden Ticket", status: "OPEN", difficulty: "expert", groomed: false, trees: true, night: false },
    { id: "summit-bowl", name: "Summit Bowl", status: "CLOSED", difficulty: "advanced", groomed: false, trees: true, night: false },
    { id: "hangar-bowl", name: "Hangar Bowl", status: "CLOSED", difficulty: "intermediate", groomed: false, trees: true, night: false },
    { id: "big-gully", name: "Big Gully", status: "CLOSED", difficulty: "expert", groomed: false, trees: true, night: false },
    { id: "bigger-gully", name: "Bigger Gully", status: "CLOSED", difficulty: "expert", groomed: false, trees: true, night: false },
    { id: "broadway-bowl", name: "Broadway Bowl", status: "CLOSED", difficulty: "intermediate", groomed: false, trees: false, night: false },
    { id: "fish-bowl", name: "Fish Bowl", status: "CLOSED", difficulty: "advanced", groomed: false, trees: true, night: false },
    { id: "way-out", name: "Way Out", status: "CLOSED", difficulty: "beginner", groomed: true, trees: false, night: false },
    { id: "buford", name: "Buford", status: "CLOSED", difficulty: "beginner", groomed: true, trees: false, night: true },
    { id: "slippy-stream", name: "Slippy Stream", status: "CLOSED", difficulty: "beginner", groomed: true, trees: false, night: true },
    { id: "peacock", name: "Peacock", status: "CLOSED", difficulty: "beginner", groomed: true, trees: false, night: true },
    { id: "fun-run", name: "Fun Run", status: "CLOSED", difficulty: "beginner", groomed: true, trees: false, night: true },
    { id: "sweet-treat", name: "Sweet Treat", status: "CLOSED", difficulty: "beginner", groomed: true, trees: false, night: true },
    { id: "stump-alley", name: "Stump Alley", status: "CLOSED", difficulty: "intermediate", groomed: true, trees: true, night: true },
    { id: "centennial", name: "Centennial", status: "CLOSED", difficulty: "advanced", groomed: false, trees: true, night: false },
    { id: "biennial", name: "Biennial", status: "CLOSED", difficulty: "advanced", groomed: false, trees: true, night: false },
    { id: "millenial", name: "Millenial", status: "CLOSED", difficulty: "advanced", groomed: false, trees: true, night: false },
    { id: "searcher", name: "Searcher", status: "CLOSED", difficulty: "intermediate", groomed: false, trees: true, night: false },
    { id: "white-lightning", name: "White Lightning", status: "CLOSED", difficulty: "advanced", groomed: false, trees: true, night: false },
    { id: "richards-return", name: "Richard's Return", status: "CLOSED", difficulty: "beginner", groomed: true, trees: true, night: false },
    { id: "head-chutes-gate-a", name: "Head Chutes Gate A", status: "CLOSED", difficulty: "expert", groomed: false, trees: true, night: false },
    { id: "head-chutes-gate-b", name: "Head Chutes Gate B", status: "CLOSED", difficulty: "expert", groomed: false, trees: true, night: false },
    { id: "head-chutes-gate-c", name: "Head Chutes Gate C", status: "CLOSED", difficulty: "expert", groomed: false, trees: true, night: false },
    { id: "bird-glade", name: "Bird Glade", status: "CLOSED", difficulty: "expert", groomed: false, trees: true, night: false },
    { id: "big-bird", name: "Big Bird", status: "CLOSED", difficulty: "expert", groomed: false, trees: true, night: false },
    { id: "roller-park", name: "Roller Park", status: "CLOSED", difficulty: "expert", groomed: false, trees: true, night: false },
    { id: "owl-glade", name: "Owl Glade", status: "CLOSED", difficulty: "expert", groomed: false, trees: true, night: false },
    { id: "whippersnapper-ridge", name: "Whippersnapper Ridge", status: "CLOSED", difficulty: "expert", groomed: false, trees: true, night: false },
    { id: "drop-in", name: "Drop In", status: "CLOSED", difficulty: "expert", groomed: false, trees: true, night: false },
    { id: "mosh-pit", name: "Mosh Pit", status: "CLOSED", difficulty: "advanced", groomed: false, trees: true, night: false }
];

public final readonly & table<EdgeRecord> key(liftId, trailId) edgeTable = table [
    { liftId: "astra-express", trailId: "blue-bird" },
    { liftId: "astra-express", trailId: "blackhawk" },
    { liftId: "astra-express", trailId: "ducks-revenge" },
    { liftId: "astra-express", trailId: "ice-streak" },
    { liftId: "astra-express", trailId: "parachute" },
    { liftId: "astra-express", trailId: "goosebumps" },

    { liftId: "jazz-cat", trailId: "goosebumps" },
    { liftId: "jazz-cat", trailId: "river-run" },
    { liftId: "jazz-cat", trailId: "ducks-revenge" },
    { liftId: "jazz-cat", trailId: "cape-cod" },
    { liftId: "jazz-cat", trailId: "grandma" },
    { liftId: "jazz-cat", trailId: "wild-child" },
    { liftId: "jazz-cat", trailId: "old-witch" },

    { liftId: "jolly-roger", trailId: "dance-fight" },
    { liftId: "jolly-roger", trailId: "sneaky-pete" },
    { liftId: "jolly-roger", trailId: "bear-cave" },
    { liftId: "jolly-roger", trailId: "humpty-dumpty" },
    { liftId: "jolly-roger", trailId: "meatball" },
    { liftId: "jolly-roger", trailId: "early-riser" },
    { liftId: "jolly-roger", trailId: "sunset" },

    { liftId: "neptune-rope", trailId: "home-run" },
    { liftId: "neptune-rope", trailId: "crosscut" },

    { liftId: "panorama", trailId: "ocean-breeze" },
    { liftId: "panorama", trailId: "songstress" },
    { liftId: "panorama", trailId: "mountain-run" },
    { liftId: "panorama", trailId: "summit-saunter" },
    { liftId: "panorama", trailId: "hemmed-slacks" },
    { liftId: "panorama", trailId: "davids-dive" },
    { liftId: "panorama", trailId: "quarry-chute" },
    { liftId: "panorama", trailId: "sunset" },
    { liftId: "panorama", trailId: "blackhawk" },

    { liftId: "prickly-peak", trailId: "crooked-chute" },
    { liftId: "prickly-peak", trailId: "marks-chute" },
    { liftId: "prickly-peak", trailId: "the-terrible-chute" },
    { liftId: "prickly-peak", trailId: "magma-chute" },
    { liftId: "prickly-peak", trailId: "saddleback-chute" },
    { liftId: "prickly-peak", trailId: "omega-chute" },
    { liftId: "prickly-peak", trailId: "adirondack-chute" },
    { liftId: "prickly-peak", trailId: "chicken-out-traverse" },

    { liftId: "snowtooth-express", trailId: "blue-streak" },
    { liftId: "snowtooth-express", trailId: "hoya-saxa" },
    { liftId: "snowtooth-express", trailId: "michigan-ave" },
    { liftId: "snowtooth-express", trailId: "parker-downhill" },
    { liftId: "snowtooth-express", trailId: "wiggle-waggle" },
    { liftId: "snowtooth-express", trailId: "meow-face" },
    { liftId: "snowtooth-express", trailId: "golden-ticket" },

    { liftId: "summit", trailId: "golden-ticket" },
    { liftId: "summit", trailId: "summit-bowl" },
    { liftId: "summit", trailId: "hangar-bowl" },
    { liftId: "summit", trailId: "big-gully" },
    { liftId: "summit", trailId: "bigger-gully" },
    { liftId: "summit", trailId: "broadway-bowl" },
    { liftId: "summit", trailId: "fish-bowl" },

    { liftId: "wallys", trailId: "buford" },
    { liftId: "wallys", trailId: "slippy-stream" },
    { liftId: "wallys", trailId: "peacock" },
    { liftId: "wallys", trailId: "fun-run" },
    { liftId: "wallys", trailId: "sweet-treat" },
    { liftId: "wallys", trailId: "stump-alley" },

    { liftId: "western-states", trailId: "centennial" },
    { liftId: "western-states", trailId: "biennial" },
    { liftId: "western-states", trailId: "millenial" },
    { liftId: "western-states", trailId: "searcher" },
    { liftId: "western-states", trailId: "white-lightning" },
    { liftId: "western-states", trailId: "richards-return" },
    { liftId: "western-states", trailId: "head-chutes-gate-a" },
    { liftId: "western-states", trailId: "head-chutes-gate-b" },
    { liftId: "western-states", trailId: "head-chutes-gate-c" },

    { liftId: "whirlybird", trailId: "bird-glade" },
    { liftId: "whirlybird", trailId: "big-bird" },
    { liftId: "whirlybird", trailId: "roller-park" },
    { liftId: "whirlybird", trailId: "owl-glade" },
    { liftId: "whirlybird", trailId: "whippersnapper-ridge" },
    { liftId: "whirlybird", trailId: "drop-in" },
    { liftId: "whirlybird", trailId: "mosh-pit" },
    { liftId: "whirlybird", trailId: "richards-return" }
];
