name: Build

on:
    repository_dispatch:
        types: [ stdlib-publish-snapshot ]
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.repository_owner == 'ballerina-platform'
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up JDK 11
                uses: actions/setup-java@v1
                with:
                    java-version: 11
            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew
            -   name: Build with Gradle
                env:
                    packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
                    packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
                run: |
                    ./gradlew publish --no-daemon
                    ./gradlew codeCoverageReport --no-daemon
            -   name: Archive Error Log
                uses: actions/upload-artifact@v2
                if: failure()
                with:
                    name: Ballerina Internal Log
                    path: graphql-ballerina/ballerina-internal.log
                    if-no-files-found: ignore
            -   name: Archive Code Coverage JSON
                uses: actions/upload-artifact@v2
                with:
                    name: Code Coverage JSON
                    path: graphql-ballerina/target/report/test_results.json
                    if-no-files-found: ignore
            -   name: Generate CodeCov Report
                uses: codecov/codecov-action@v1
            -   name: Dispatch Dependent Module Builds
                if: github.event.action != 'stdlib-publish-snapshot'
                run: |
                    echo "Triggering dependent module builds..." && \
                    curl -u ${{ secrets.BALLERINA_BOT_USERNAME }} -X POST \
                    https://api.github.com/repos/ballerina-platform/ballerina-standard-library/dispatches \
                    -H 'Accept: application/vnd.github.v3+json' \
                    -H 'Authorization: token ${{ secrets.BALLERINA_BOT_TOKEN }}' \
                    --data '{
                        "event_type": "stdlib-module-push",
                        "client_payload": {
                            "module": "${{ github.repository }}"
                        }
                    }'
